const { Client, GatewayIntentBits, REST, Routes, SlashCommandBuilder } = require('discord.js');

const ALLOWED_USERS = ['542927955903512587', '1515213214110060618', '1220053148874575994'];

async function startBot(pool, generateKeyString, token) {
  if (!token) {
    console.log('[BOT] No DISCORD_BOT_TOKEN provided. Bot is disabled.');
    return;
  }

  const client = new Client({ intents: [GatewayIntentBits.Guilds] });

  const commands = [
    new SlashCommandBuilder()
      .setName('genkey')
      .setDescription('Generates a new API key and DMs it to the user.')
      .addStringOption(option =>
        option.setName('length')
          .setDescription('Duration in days (e.g. 1, 7, 30, or 9999 for Lifetime)')
          .setRequired(true))
      .addStringOption(option =>
        option.setName('plan')
          .setDescription('The plan type')
          .setRequired(true)
          .addChoices(
            { name: 'Bronze', value: 'Bronze' },
            { name: 'Silver', value: 'Silver' },
            { name: 'Gold', value: 'Gold' },
            { name: 'Diamond', value: 'Diamond' },
            { name: 'Lifetime', value: 'Lifetime' }
          ))
      .addUserOption(option =>
        option.setName('user')
          .setDescription('The user to DM the key to')
          .setRequired(true))
  ];

  const rest = new REST({ version: '10' }).setToken(token);

  client.on('ready', async () => {
    console.log(`[BOT] Logged in as ${client.user.tag}!`);
    try {
      console.log('[BOT] Refreshing application (/) commands.');
      await rest.put(
        Routes.applicationCommands(client.user.id),
        { body: commands },
      );
      console.log('[BOT] Successfully reloaded application (/) commands.');
    } catch (error) {
      console.error(error);
    }
  });

  client.on('interactionCreate', async interaction => {
    if (!interaction.isChatInputCommand()) return;
    if (interaction.commandName !== 'genkey') return;

    if (!ALLOWED_USERS.includes(interaction.user.id)) {
      return interaction.reply({ content: '⛔ You are not authorized to use this command.', ephemeral: true });
    }

    const lengthInput = interaction.options.getString('length');
    const plan = interaction.options.getString('plan');
    const targetUser = interaction.options.getUser('user');

    const durationDays = parseInt(lengthInput);
    if (isNaN(durationDays) || durationDays <= 0) {
      return interaction.reply({ content: 'Invalid length provided. Please provide a valid number of days.', ephemeral: true });
    }

    await interaction.deferReply({ ephemeral: true });

    try {
      const email = targetUser.username;
      const keyStr = generateKeyString(email, plan);
      
      const newKey = {
        id: Date.now(),
        key: keyStr,
        plan: plan,
        email: email,
        durationDays: durationDays,
        expires: durationDays === 9999 ? null : Date.now() + (durationDays * 24 * 60 * 60 * 1000)
      };

      await pool.query(
        'INSERT INTO api_keys (id, key, plan, email, duration_days, expires) VALUES ($1, $2, $3, $4, $5, $6)',
        [newKey.id, newKey.key, newKey.plan, newKey.email, newKey.durationDays, newKey.expires]
      );

      // DM the user
      try {
        await targetUser.send(`## Welcome to Reveal Intelligence! 🚀\nYour **${plan}** API Key has been generated by an admin.\n\n**Your Key:** \`${newKey.key}\`\n**Duration:** ${durationDays === 9999 ? 'Lifetime' : durationDays + ' Days'}\n\n*Keep this key safe and do not share it!*`);
        await interaction.editReply({ content: `✅ Successfully generated a **${plan}** key for ${durationDays} days and DM'd it to ${targetUser}.` });
      } catch (dmError) {
        console.error('Failed to DM user:', dmError);
        await interaction.editReply({ content: `✅ Successfully generated the key, but **failed to DM the user**. Their DMs might be closed.\n\nKey: \`${newKey.key}\`` });
      }

    } catch (error) {
      console.error('Database Error in Bot:', error);
      await interaction.editReply({ content: '❌ Failed to generate key due to a database error.' });
    }
  });

  client.login(token).catch(err => {
    console.error('[BOT] Failed to login:', err);
  });
}

module.exports = { startBot };
